// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Files struct {
	ID           int32          `db:"id" json:"id"`
	FileName     string         `db:"file_name" json:"file_name"`
	OriginalName string         `db:"original_name" json:"original_name"`
	FilePath     string         `db:"file_path" json:"file_path"`
	FileSize     int64          `db:"file_size" json:"file_size"`
	MimeType     string         `db:"mime_type" json:"mime_type"`
	Description  sql.NullString `db:"description" json:"description"`
	Category     sql.NullString `db:"category" json:"category"`
	UploadedBy   int32          `db:"uploaded_by" json:"uploaded_by"`
	CreatedAt    sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt    sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type Users struct {
	ID        int32        `db:"id" json:"id"`
	Name      string       `db:"name" json:"name"`
	Email     string       `db:"email" json:"email"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}
