// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (Files, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (Users, error)
	DeleteFile(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetAllFiles(ctx context.Context) ([]Files, error)
	GetAllUsers(ctx context.Context) ([]Users, error)
	GetFile(ctx context.Context, id int32) (Files, error)
	GetFilesByUser(ctx context.Context, uploadedBy int32) ([]Files, error)
	GetUser(ctx context.Context, id int32) (Users, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByEmailWithPassword(ctx context.Context, email string) (Users, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]Users, error)
	UpdateFile(ctx context.Context, arg UpdateFileParams) (Files, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
